server:
  port: 13000
  servlet:
    context-path : /osapi
spring:
  datasource:
    url: jdbc:mysql://localhost/osdb?createDatabaseIfNotExist=true
    password: letmein0
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
logging:
  level:
    org.springframework: DEBUG