origins: http://localhost,http://localhost:13082,http://127.0.0.1:13082,https://localhost, 
keycloak-issuer: http://localhost/auth/realms/openslice


server:
  port: 13000
  servlet:
    context-path : /osapi
  error:
    include-message: always
  ssl:
    enabled: false
    
springdoc:
  version: '@springdoc.version@'
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    oauth:
      client-id: osapiWebClientId
      clientsecret: "secret"
      use-pkce-with-authorization-code-grant: false
  oAuthFlow:
    authorizationUrl: http://localhost/auth/realms/openslice/protocol/openid-connect/auth
    tokenUrl: http://localhost/auth/realms/openslice/protocol/openid-connect/token
  show-actuator: true

spring-addons:
  issuers:
  - uri: ${keycloak-issuer}
    username-json-path: $.preferred_username
    claims:
    - jsonPath: $.realm_access.roles
    - jsonPath: $.resource_access.*.roles

    
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: openslice-portal-api
  datasource:
    url: jdbc:mysql://localhost/osdb?createDatabaseIfNotExist=true
    password: letmein
    username: root
    hikari:
       minimumIdle: 2
       maximumPoolSize: 40
       idleTimeout: 120000
       connectionTimeout: 400000
       leakDetectionThreshold: 100000
  jpa:
    database-platform: portal.api.LocalMysqlDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true 
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  resources:
    add-mappings: true
logging:
  level:
    root: INFO
    portal.api: INFO
    org.springframework: INFO
    org.apache.camel: INFO 
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}    

keycloak:
  realm: openslice
  auth-server-url: http://localhost:28080/auth
  ssl-required: none
  resource: admin-cli
  credentials:
    secret: none
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username

keycloak-internal-auth-server-url: http://localhost:28080/auth
keycloak-admin-password: Pa55w0rd
    
swagger:
  authserver: http://localhost:28080/auth/realms/openslice
  clientid: "osapiWebClientId"
  clientsecret: "secret"
  
oauthsign:
   key: "EK97Y7Y9WPGG1MEG"


#QUEUE MESSSAGES WITH VNFNSD CATALOG
NFV_CATALOG_GET_NSD_BY_ID: "jms:queue:NFVCATALOG.GET.NSD_BY_ID" 
NFV_CATALOG_DEPLOY_NSD_REQ: "jms:queue:NFVCATALOG.DEPLOY.NSD_REQ"
NFV_CATALOG_UPD_DEPLOYMENT_BY_ID: "jms:queue:NFVCATALOG.UPD.DEPLOYMENT_BY_ID"
NFV_CATALOG_GET_DEPLOYMENT_BY_ID: "jms:queue:NFVCATALOG.GET.DEPLOYMENT_BY_ID"
GET_USER_BY_USERNAME: "jms:queue:GET.USER_BY_USERNAME"
