server:
  port: 13000
  servlet:
    context-path : /osapi
spring:
  datasource:
    url: jdbc:mysql://localhost/osdb
    password: letmein0
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true