server:
  port: 13000
  servlet:
    context-path : /osapi
spring:
  profiles: default
  application:
    name: openslice-portal-api
  datasource:
    url: jdbc:mysql://localhost/osdb?createDatabaseIfNotExist=true
    password: letmein0
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  cloud:
    consul:
      enabled: true
      host: http://localhost:8500
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: openslice
        data-key: osdata
        profileSeparator: '::'
        format: yaml        
      discovery:
        tags: openslice-microservice
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 120s
logging:
  level:
    root: INFO
    portal.api: INFO
    org.springframework: INFO
    org.apache.camel: INFO 
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
    
swagger:
  authserver: "http://localhost:13081/osapi-oauth-server"
  clientid: "osapiWebClientId"
  clientsecret: "secret"
  
oauthsign:
   key: "EK97Y7Y9WPGG1MEG"


#QUEUE MESSSAGES WITH VNFNSD CATALOG
VNFNSD_CATALOG_GET_NSD_BY_ID: "jms:queue:VNFNSDCATALOG.GET.NSD_BY_ID"  